#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# UI (Primary Service)
cd /Users/jkneen/Documents/GitHub/atomicbot/ui && npm run dev &
UI_PID=$!
wait_for_service 3000 "UI"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  UI:  http://localhost:3000"
echo ""
echo "Note: Gateway backend should be started separately if needed:"
echo "  cd /Users/jkneen/Documents/GitHub/atomicbot && pnpm dev"
echo ""
echo "To run tests:"
echo "  cd /Users/jkneen/Documents/GitHub/atomicbot/ui && npm test"
echo ""
echo "To build:"
echo "  cd /Users/jkneen/Documents/GitHub/atomicbot/ui && npm run build"
echo ""

# Keep script running
echo "Press Ctrl+C to stop services..."
wait
