import type { ErrorShape } from "./types.js";

export const ErrorCodes = {
  NOT_LINKED: "NOT_LINKED",
  NOT_PAIRED: "NOT_PAIRED",
  AGENT_TIMEOUT: "AGENT_TIMEOUT",
  INVALID_REQUEST: "INVALID_REQUEST",
  UNAVAILABLE: "UNAVAILABLE",
  // Worktree error codes
  AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  PATH_OUTSIDE_WORKSPACE: "PATH_OUTSIDE_WORKSPACE",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  DISK_FULL: "DISK_FULL",
  INVALID_PATH: "INVALID_PATH",
  INVALID_ENCODING: "INVALID_ENCODING",
  FILE_EXISTS: "FILE_EXISTS",
  DIRECTORY_NOT_EMPTY: "DIRECTORY_NOT_EMPTY",
  NOT_A_FILE: "NOT_A_FILE",
  NOT_A_DIRECTORY: "NOT_A_DIRECTORY",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  PARENT_NOT_FOUND: "PARENT_NOT_FOUND",
  CANNOT_DELETE_ROOT: "CANNOT_DELETE_ROOT",
  SOURCE_NOT_FOUND: "SOURCE_NOT_FOUND",
  DESTINATION_EXISTS: "DESTINATION_EXISTS",
  CANNOT_MOVE_TO_SUBDIRECTORY: "CANNOT_MOVE_TO_SUBDIRECTORY",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export function errorShape(
  code: ErrorCode,
  message: string,
  opts?: { details?: unknown; retryable?: boolean; retryAfterMs?: number },
): ErrorShape {
  return {
    code,
    message,
    ...opts,
  };
}
