packages:
  - .
  - ui

onlyBuiltDependencies:
  - '@whiskeysockets/baileys'
  - authenticate-pam
  - esbuild
  - protobufjs
  - sharp

patchedDependencies:
  '@mariozechner/pi-ai@0.42.2': patches/@[redacted-email]
