packages:
  - .
  - ui
  - packages/*
  - extensions/*
  - apps/*

onlyBuiltDependencies:
  - "@lydell/node-pty"
  - "@matrix-org/matrix-sdk-crypto-nodejs"
  - "@napi-rs/canvas"
  - "@whiskeysockets/baileys"
  - authenticate-pam
  - better-sqlite3
  - cpu-features
  - electron
  - electron-winstaller
  - esbuild
  - fs-xattr
  - macos-alias
  - node-llama-cpp
  - protobufjs
  - sharp
  - ssh2
