import { StyleDatabase } from "./style-db.js";
import type { AdjustmentStats } from "./style-db.js";

/**
 * Generate a human-readable "Editing DNA" report from the style database.
 * This is the photographer's style fingerprint — shareable and interesting.
 */
export function generateStyleReport(dbPath: string): string {
  const db = new StyleDatabase(dbPath);
  const scenarios = db.listScenarios();
  const totalEdits = db.getEditCount();
  const lastIngest = db.getMeta("last_ingest");
  const catalogPath = db.getMeta("catalog_path");

  const lines: string[] = [];

  lines.push("# Your Editing DNA");
  lines.push(`## Generated by The Lab — Department of Vibe`);
  lines.push("");
  lines.push(`**Total edits analyzed:** ${totalEdits}`);
  lines.push(`**Scenarios discovered:** ${scenarios.length}`);
  lines.push(`**Last updated:** ${lastIngest ?? "never"}`);
  if (catalogPath) {
    lines.push(`**Source catalog:** ${catalogPath}`);
  }
  lines.push("");

  // Global tendencies
  lines.push("---");
  lines.push("");
  lines.push("## Your Signature Moves");
  lines.push("");

  const globalTendencies = computeGlobalTendencies(db, scenarios);
  if (globalTendencies.length > 0) {
    lines.push("Across all your photos, you consistently:");
    lines.push("");
    for (const tendency of globalTendencies) {
      lines.push(`- ${tendency}`);
    }
    lines.push("");
  }

  // Per-scenario breakdown
  lines.push("---");
  lines.push("");
  lines.push("## Scenario Breakdown");
  lines.push("");

  for (const scenario of scenarios) {
    if (scenario.sampleCount < 2) {
      continue;
    }

    const profile = db.getProfile(scenario.key);
    if (!profile) {
      continue;
    }

    lines.push(`### ${scenario.label}`);
    lines.push(`*${scenario.sampleCount} photos analyzed*`);
    lines.push("");

    const topMoves = Object.entries(profile.adjustments)
      .filter(([, stats]) => Math.abs(stats.median) > 0.5)
      .toSorted((a, b) => Math.abs(b[1].median) - Math.abs(a[1].median));

    if (topMoves.length === 0) {
      lines.push("Minimal adjustments — you tend to keep these close to camera defaults.");
      lines.push("");
      continue;
    }

    lines.push("| Control | Typical | Range | Consistency |");
    lines.push("|---------|---------|-------|-------------|");

    for (const [control, stats] of topMoves.slice(0, 8)) {
      const sign = stats.median > 0 ? "+" : "";
      const range = `${stats.min.toFixed(0)} to ${stats.max.toFixed(0)}`;
      const consistency = describeConsistency(stats);
      lines.push(`| ${control} | ${sign}${stats.median.toFixed(1)} | ${range} | ${consistency} |`);
    }

    lines.push("");

    // Add narrative description
    const narrative = describeScenarioStyle(scenario.label, topMoves);
    if (narrative) {
      lines.push(`> ${narrative}`);
      lines.push("");
    }
  }

  // Style evolution hint
  lines.push("---");
  lines.push("");
  lines.push("## What This Means");
  lines.push("");
  lines.push("This profile is your editing fingerprint. The Lab uses it to edit new photos");
  lines.push("the way you would — matching your specific adjustments for each type of scene.");
  lines.push("");
  lines.push("The more you edit, the more accurate it gets. Run `learn` again after editing");
  lines.push("sessions to keep your profile current.");
  lines.push("");

  db.close();
  return lines.join("\n");
}

function computeGlobalTendencies(
  db: StyleDatabase,
  scenarios: Array<{ key: string; label: string; sampleCount: number }>,
): string[] {
  const tendencies: string[] = [];
  const globalStats: Record<string, { sum: number; count: number }> = {};

  for (const scenario of scenarios) {
    const profile = db.getProfile(scenario.key);
    if (!profile) {
      continue;
    }

    for (const [control, stats] of Object.entries(profile.adjustments)) {
      if (!globalStats[control]) {
        globalStats[control] = { sum: 0, count: 0 };
      }
      globalStats[control].sum += stats.median * stats.sampleCount;
      globalStats[control].count += stats.sampleCount;
    }
  }

  const weighted = Object.entries(globalStats)
    .map(([control, { sum, count }]) => ({
      control,
      avg: count > 0 ? sum / count : 0,
    }))
    .filter((e) => Math.abs(e.avg) > 1)
    .toSorted((a, b) => Math.abs(b.avg) - Math.abs(a.avg));

  for (const { control, avg } of weighted.slice(0, 6)) {
    tendencies.push(describeGlobalTendency(control, avg));
  }

  return tendencies;
}

function describeGlobalTendency(control: string, avg: number): string {
  const direction = avg > 0 ? "increase" : "decrease";
  const magnitude = Math.abs(avg);
  const intensity = magnitude > 20 ? "significantly" : magnitude > 5 ? "moderately" : "slightly";

  const labels: Record<string, string> = {
    exposure: `${intensity} ${direction} exposure (${avg > 0 ? "brighter" : "darker"} than camera)`,
    temp:
      avg > 0
        ? `warm up white balance by ~${magnitude.toFixed(0)}K`
        : `cool down white balance by ~${Math.abs(avg).toFixed(0)}K`,
    tint: `shift tint ${avg > 0 ? "toward magenta" : "toward green"}`,
    shadows: `${intensity} ${avg > 0 ? "lift" : "crush"} shadows`,
    highlights: `${intensity} ${avg > 0 ? "boost" : "pull down"} highlights`,
    contrast: `${intensity} ${avg > 0 ? "add" : "reduce"} contrast`,
    clarity: `${intensity} ${avg > 0 ? "add" : "reduce"} clarity`,
    vibrance: `${intensity} ${avg > 0 ? "boost" : "reduce"} vibrance`,
    saturation: `${intensity} ${avg > 0 ? "boost" : "desaturate"} colors`,
    dehaze: `${intensity} ${avg > 0 ? "add" : "reduce"} dehaze`,
    texture: `${intensity} ${avg > 0 ? "add" : "soften"} texture`,
    whites: `${intensity} ${avg > 0 ? "push" : "pull"} whites`,
    blacks: `${intensity} ${avg > 0 ? "lift" : "crush"} blacks`,
    grain_amount: `add grain (amount ~${magnitude.toFixed(0)})`,
    vignette_amount: avg < 0 ? "add vignette" : "remove vignette",
  };

  return labels[control] ?? `${intensity} ${direction} ${control.replace(/_/g, " ")}`;
}

function describeConsistency(stats: AdjustmentStats): string {
  if (stats.sampleCount < 3) {
    return "too few samples";
  }
  const cv = Math.abs(stats.median) > 0.1 ? stats.stdDev / Math.abs(stats.median) : stats.stdDev;

  if (cv < 0.3) {
    return "very consistent";
  }
  if (cv < 0.6) {
    return "consistent";
  }
  if (cv < 1.0) {
    return "moderate";
  }
  return "varies widely";
}

function describeScenarioStyle(
  label: string,
  topMoves: Array<[string, AdjustmentStats]>,
): string | null {
  if (topMoves.length === 0) {
    return null;
  }

  const parts: string[] = [];
  const top3 = topMoves.slice(0, 3);

  for (const [control, stats] of top3) {
    const sign = stats.median > 0 ? "+" : "";
    parts.push(`${control.replace(/_/g, " ")} ${sign}${stats.median.toFixed(1)}`);
  }

  return `For ${label}: your go-to moves are ${parts.join(", ")}.`;
}

/**
 * Generate a session summary report after an editing session completes.
 */
export function generateSessionReport(stats: {
  totalImages: number;
  completed: number;
  flagged: number;
  errors: number;
  elapsedMs: number;
  avgMsPerImage: number;
  scenariosUsed: number;
  scenarioBreakdown?: Record<string, number>;
  flaggedImages?: Array<{ imageId: string; reason: string }>;
}): string {
  const lines: string[] = [];
  const savedMinutes = Math.round(stats.completed * 2.5);
  const savedHours = (savedMinutes / 60).toFixed(1);

  const hours = Math.floor(stats.elapsedMs / 3_600_000);
  const minutes = Math.floor((stats.elapsedMs % 3_600_000) / 60_000);
  const timeStr = hours > 0 ? `${hours}h ${minutes}m` : `${minutes}m`;

  lines.push("# The Lab — Session Report");
  lines.push(
    `## ${new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}`,
  );
  lines.push("");
  lines.push("### Summary");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total images | ${stats.totalImages} |`);
  lines.push(`| Edited | ${stats.completed} |`);
  lines.push(`| Flagged for review | ${stats.flagged} |`);
  lines.push(`| Errors | ${stats.errors} |`);
  lines.push(`| Scenarios used | ${stats.scenariosUsed} |`);
  lines.push(`| Processing time | ${timeStr} |`);
  lines.push(`| Avg per image | ${(stats.avgMsPerImage / 1000).toFixed(1)}s |`);
  lines.push(`| **Estimated time saved** | **~${savedHours} hours** |`);
  lines.push("");

  if (stats.scenarioBreakdown && Object.keys(stats.scenarioBreakdown).length > 0) {
    lines.push("### Scenarios Used");
    lines.push("");
    const sorted = Object.entries(stats.scenarioBreakdown).toSorted((a, b) => b[1] - a[1]);

    for (const [scenario, count] of sorted) {
      const pct = Math.round((count / stats.completed) * 100);
      lines.push(`- **${scenario}**: ${count} photos (${pct}%)`);
    }
    lines.push("");
  }

  if (stats.flaggedImages && stats.flaggedImages.length > 0) {
    lines.push("### Flagged for Review");
    lines.push("");
    lines.push("These images need your eye:");
    lines.push("");
    for (const { imageId, reason } of stats.flaggedImages) {
      lines.push(`- **${imageId}**: ${reason}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by The Lab — Department of Vibe*");

  return lines.join("\n");
}
