"""OpenClaw configuration module.

This module provides configuration loading, validation, and management.
"""

from .defaults import (
    apply_defaults,
    apply_gateway_defaults,
    apply_logging_defaults,
    apply_session_defaults,
    apply_telegram_defaults,
)
from .env_substitution import MissingEnvVarError, substitute_env_vars
from .loader import (
    ConfigLoadError,
    ConfigParseError,
    ConfigValidationError,
    load_config_file,
    load_config_sync,
    parse_config_file,
    read_config_file_snapshot,
)
from .paths import (
    ensure_state_dir,
    expand_home_prefix,
    resolve_config_path,
    resolve_default_config_candidates,
    resolve_home_dir,
    resolve_state_dir,
)
from .types import (
    BlockStreamingChunkConfig,
    BlockStreamingCoalesceConfig,
    ConfigFileSnapshot,
    ConfigValidationIssue,
    EnvConfig,
    EnvShellConfig,
    GatewayConfig,
    IdentityConfig,
    LoggingConfig,
    MarkdownConfig,
    MetaConfig,
    ModelCompatConfig,
    ModelCostConfig,
    ModelDefinitionConfig,
    ModelProviderConfig,
    ModelsConfig,
    OpenClawConfig,
    OutboundRetryConfig,
    SessionAgentToAgentConfig,
    SessionConfig,
    SessionMaintenanceConfig,
    SessionResetByTypeConfig,
    SessionResetConfig,
    SessionSendPolicyConfig,
    SessionSendPolicyMatch,
    SessionSendPolicyRule,
    TelegramAccountConfig,
    TelegramActionConfig,
    TelegramConfig,
    TelegramCustomCommand,
    TelegramGroupConfig,
    TelegramNetworkConfig,
    TelegramTopicConfig,
)

__all__ = [
    # Loader
    "load_config_file",
    "load_config_sync",
    "read_config_file_snapshot",
    "parse_config_file",
    "ConfigLoadError",
    "ConfigParseError",
    "ConfigValidationError",
    # Env substitution
    "substitute_env_vars",
    "MissingEnvVarError",
    # Paths
    "resolve_config_path",
    "resolve_state_dir",
    "resolve_home_dir",
    "expand_home_prefix",
    "resolve_default_config_candidates",
    "ensure_state_dir",
    # Defaults
    "apply_defaults",
    "apply_logging_defaults",
    "apply_session_defaults",
    "apply_telegram_defaults",
    "apply_gateway_defaults",
    # Types
    "OpenClawConfig",
    "ConfigFileSnapshot",
    "ConfigValidationIssue",
    "MetaConfig",
    "EnvConfig",
    "EnvShellConfig",
    "LoggingConfig",
    "SessionConfig",
    "SessionResetConfig",
    "SessionResetByTypeConfig",
    "SessionSendPolicyConfig",
    "SessionSendPolicyMatch",
    "SessionSendPolicyRule",
    "SessionMaintenanceConfig",
    "SessionAgentToAgentConfig",
    "ModelCostConfig",
    "ModelCompatConfig",
    "ModelDefinitionConfig",
    "ModelProviderConfig",
    "ModelsConfig",
    "TelegramConfig",
    "TelegramAccountConfig",
    "TelegramGroupConfig",
    "TelegramTopicConfig",
    "TelegramActionConfig",
    "TelegramNetworkConfig",
    "TelegramCustomCommand",
    "MarkdownConfig",
    "OutboundRetryConfig",
    "BlockStreamingChunkConfig",
    "BlockStreamingCoalesceConfig",
    "GatewayConfig",
    "IdentityConfig",
]
