export const browserCoreExamples = [
  "amigo browser status",
  "amigo browser start",
  "amigo browser stop",
  "amigo browser tabs",
  "amigo browser open https://example.com",
  "amigo browser focus abcd1234",
  "amigo browser close abcd1234",
  "amigo browser screenshot",
  "amigo browser screenshot --full-page",
  "amigo browser screenshot --ref 12",
  "amigo browser snapshot",
  "amigo browser snapshot --format aria --limit 200",
  "amigo browser snapshot --efficient",
  "amigo browser snapshot --labels",
];

export const browserActionExamples = [
  "amigo browser navigate https://example.com",
  "amigo browser resize 1280 720",
  "amigo browser click 12 --double",
  'amigo browser type 23 "hello" --submit',
  "amigo browser press Enter",
  "amigo browser hover 44",
  "amigo browser drag 10 11",
  "amigo browser select 9 OptionA OptionB",
  "amigo browser upload /tmp/file.pdf",
  'amigo browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "amigo browser dialog --accept",
  'amigo browser wait --text "Done"',
  "amigo browser evaluate --fn '(el) => el.textContent' --ref 7",
  "amigo browser console --level error",
  "amigo browser pdf",
];
