/**
 * Cloud.ru FM Onboarding Utilities
 *
 * Helper functions for the Cloud.ru FM wizard flow:
 * - Model preset resolution
 * - Docker Compose file generation
 * - .env file management
 * - .gitignore management
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import type { AuthChoice } from "./onboard-types.js";
import { generateProxyDockerCompose } from "../agents/cloudru-proxy-template.js";
import {
  CLOUDRU_FM_PRESETS,
  CLOUDRU_COMPOSE_FILENAME,
  type CloudruModelPreset,
} from "../config/cloudru-fm.constants.js";

export type { CloudruModelPreset };

/**
 * Resolve an AuthChoice to a CloudruModelPreset.
 * Throws if the choice is not a valid cloudru-fm choice.
 */
export function resolveCloudruModelPreset(choice: AuthChoice | string): CloudruModelPreset {
  const preset = CLOUDRU_FM_PRESETS[choice];
  if (!preset) {
    throw new Error(
      `Unknown Cloud.ru FM preset: "${choice}". ` +
        `Valid choices: ${Object.keys(CLOUDRU_FM_PRESETS).join(", ")}`,
    );
  }
  return preset;
}

/**
 * Write the Docker Compose file for the proxy.
 * Uses the security-hardened template from cloudru-proxy-template.
 */
export async function writeDockerComposeFile(params: {
  workspaceDir: string;
  port: number;
  preset: CloudruModelPreset;
}): Promise<string> {
  const composePath = path.join(params.workspaceDir, CLOUDRU_COMPOSE_FILENAME);
  const content = generateProxyDockerCompose({
    port: params.port,
    preset: params.preset,
  });
  await fs.writeFile(composePath, content, { encoding: "utf-8" });
  return composePath;
}

/**
 * Write .env file with the Cloud.ru API key.
 * Uses restrictive permissions (0o600) to prevent credential leakage.
 */
export async function writeCloudruEnvFile(params: {
  apiKey: string;
  workspaceDir: string;
}): Promise<string> {
  const envPath = path.join(params.workspaceDir, ".env");
  const content = `# Cloud.ru Foundation Models API key\n# Auto-generated by OpenClaw wizard — do NOT commit this file\nCLOUDRU_API_KEY=${params.apiKey}\n`;
  await fs.writeFile(envPath, content, { encoding: "utf-8", mode: 0o600 });
  return envPath;
}

/**
 * Idempotently add entries to .gitignore.
 * Creates .gitignore if it doesn't exist.
 */
export async function ensureGitignoreEntries(params: {
  workspaceDir: string;
  entries: string[];
}): Promise<void> {
  const gitignorePath = path.join(params.workspaceDir, ".gitignore");

  let existing = "";
  try {
    existing = await fs.readFile(gitignorePath, "utf-8");
  } catch {
    // File doesn't exist yet — will be created
  }

  const existingLines = new Set(
    existing
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean),
  );

  const missing = params.entries.filter((entry) => !existingLines.has(entry));
  if (missing.length === 0) {
    return;
  }

  const suffix =
    (existing.endsWith("\n") || existing === "" ? "" : "\n") +
    "\n# Cloud.ru FM integration (auto-added)\n" +
    missing.join("\n") +
    "\n";

  await fs.appendFile(gitignorePath, suffix, "utf-8");
}
