# DigitalOcean App Platform deployment config
name: shopify-smart-restock-bot
services:
- name: web
  source_dir: /
  github:
    repo: GMTekAI/shopify-smart-restock-bot  
    branch: main
    deploy_on_push: true
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  health_check:
    http_path: /health
  env_vars:
  - key: NODE_ENV
    value: production
  - key: PORT  
    value: "3000"