#!/usr/bin/env bash
set -euo pipefail

# Gateway Auth Enforcement — Phase 1 Issue Creation
# Generated by sprint-planner agent on 2026-02-18

REPO="openclaw/openclaw"

echo "Creating Phase 1 issues for Gateway Auth Enforcement..."
echo ""

# Issue 1: Task 1.1 - Create Security Requirements Module
echo "Creating issue for Task 1.1..."
gh issue create \
  --repo "$REPO" \
  --title "[GW-Auth Phase 1.1] Create Security Requirements Module" \
  --label "security,gateway,breaking-change" \
  --body - <<'EOF'
## Context

Part of the [Gateway Auth Enforcement Roadmap](https://github.com/openclaw/openclaw/blob/main/docs/security/GATEWAY_AUTH_ENFORCEMENT_ROADMAP.md#phase-1-security-requirements-schema).

**Phase 1, Task 1.1**: Define mandatory security configuration fields that must be present before gateway starts.

## Acceptance Criteria

- [ ] Create new module `src/config/security-requirements.ts`
- [ ] Define `SecurityRequirement` type with fields: `field`, `description`, `check`, `remediation`
- [ ] Create `MANDATORY_SECURITY_REQUIREMENTS` array with:
  - `gateway.auth.mode` requirement (token/password/trusted-proxy)
  - `gateway.auth.token|password` credential requirement
  - `gateway.securityConfigured` acknowledgement requirement
- [ ] Implement `validateSecurityRequirements(config)` function
- [ ] Implement `formatSecurityFailures(failures)` function
- [ ] Create test file `src/config/security-requirements.test.ts`
- [ ] All tests pass

## Target Files

- `src/config/security-requirements.ts` (create new)
- `src/config/security-requirements.test.ts` (create new)

## Verification Commands

```bash
pnpm tsgo
pnpm check
pnpm test src/config/security-requirements.test.ts
```

## Assigned Agent

`security-schema`

## Dependencies

None (foundation task)

## Implementation Notes

See roadmap Phase 1, Task 1.1 for full TypeScript implementation example.

Key requirements:
- Check `gateway.auth.mode` is one of: `token`, `password`, or `trusted-proxy`
- Verify credentials exist (token, password, or trustedProxy.userHeader)
- Check environment variables if config values missing
- Require `gateway.securityConfigured === true` flag
EOF

echo "✓ Created Task 1.1 issue"
echo ""

# Issue 2: Task 1.2 - Add securityConfigured flag to config schema
echo "Creating issue for Task 1.2..."
gh issue create \
  --repo "$REPO" \
  --title "[GW-Auth Phase 1.2] Add securityConfigured Flag to Config Schema" \
  --label "security,gateway,breaking-change" \
  --body - <<'EOF'
## Context

Part of the [Gateway Auth Enforcement Roadmap](https://github.com/openclaw/openclaw/blob/main/docs/security/GATEWAY_AUTH_ENFORCEMENT_ROADMAP.md#phase-1-security-requirements-schema).

**Phase 1, Task 1.2**: Add mandatory `gateway.securityConfigured` boolean field to config schema.

## Acceptance Criteria

- [ ] Add `securityConfigured` field to `GatewayConfigSchema` in `src/config/config.ts`
- [ ] Field type: `Type.Optional(Type.Boolean())`
- [ ] Include description: "Set to true after completing security configuration. Gateway will not start without this."
- [ ] TypeScript checks pass
- [ ] Existing config tests still pass

## Target Files

- `src/config/config.ts`

## Verification Commands

```bash
pnpm tsgo
pnpm check
pnpm test src/config/config.test.ts
```

## Assigned Agent

`security-schema`

## Dependencies

None (foundation task, can be done in parallel with Task 1.1)

## Implementation Notes

Add to the `GatewayConfigSchema` TypeBox schema:

```typescript
securityConfigured: Type.Optional(Type.Boolean({
  description: "Set to true after completing security configuration. Gateway will not start without this.",
})),
```

This field acts as an acknowledgement flag that security has been reviewed and configured. The gateway will refuse to start without this flag being `true` once Phase 3 is implemented.
EOF

echo "✓ Created Task 1.2 issue"
echo ""

echo "✅ Phase 1 issues created successfully"
echo ""
echo "Next steps:"
echo "1. Issues should now be visible at: https://github.com/$REPO/issues"
echo "2. Agent profiles can be assigned to these issues"
echo "3. Update sprint tracker after work begins"
