import type { ModelDefinitionConfig } from "../config/types.models.js";

const AZURE_FOUNDRY_ZERO_COST = {
  input: 0,
  output: 0,
  cacheRead: 0,
  cacheWrite: 0,
};

export const AZURE_FOUNDRY_MODEL_CATALOG: ModelDefinitionConfig[] = [
  {
    id: "gpt-4o",
    name: "GPT-4o",
    reasoning: false,
    input: ["text", "image"],
    contextWindow: 128000,
    maxTokens: 16384,
    cost: AZURE_FOUNDRY_ZERO_COST,
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    reasoning: false,
    input: ["text", "image"],
    contextWindow: 128000,
    maxTokens: 16384,
    cost: AZURE_FOUNDRY_ZERO_COST,
  },
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    reasoning: false,
    input: ["text", "image"],
    contextWindow: 1047576,
    maxTokens: 32768,
    cost: AZURE_FOUNDRY_ZERO_COST,
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    reasoning: false,
    input: ["text", "image"],
    contextWindow: 1047576,
    maxTokens: 32768,
    cost: AZURE_FOUNDRY_ZERO_COST,
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    reasoning: false,
    input: ["text", "image"],
    contextWindow: 1047576,
    maxTokens: 32768,
    cost: AZURE_FOUNDRY_ZERO_COST,
  },
  {
    id: "o3-mini",
    name: "o3-mini",
    reasoning: true,
    input: ["text"],
    contextWindow: 200000,
    maxTokens: 100000,
    cost: AZURE_FOUNDRY_ZERO_COST,
  },
  {
    id: "o4-mini",
    name: "o4-mini",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 200000,
    maxTokens: 100000,
    cost: AZURE_FOUNDRY_ZERO_COST,
  },
  {
    id: "DeepSeek-R1",
    name: "DeepSeek R1",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 8192,
    cost: AZURE_FOUNDRY_ZERO_COST,
  },
  {
    id: "Phi-4",
    name: "Phi-4",
    reasoning: false,
    input: ["text"],
    contextWindow: 16384,
    maxTokens: 4096,
    cost: AZURE_FOUNDRY_ZERO_COST,
  },
  {
    id: "Mistral-large-2411",
    name: "Mistral Large 2411",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 8192,
    cost: AZURE_FOUNDRY_ZERO_COST,
  },
  {
    id: "Meta-Llama-3.1-405B-Instruct",
    name: "Meta Llama 3.1 405B Instruct",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 8192,
    cost: AZURE_FOUNDRY_ZERO_COST,
  },
  {
    id: "Cohere-command-r-plus-08-2024",
    name: "Cohere Command R+ (08-2024)",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 4096,
    cost: AZURE_FOUNDRY_ZERO_COST,
  },
];

export function buildAzureFoundryModelDefinition(
  model: (typeof AZURE_FOUNDRY_MODEL_CATALOG)[number],
): ModelDefinitionConfig {
  return {
    id: model.id,
    name: model.name,
    api: "openai-completions",
    reasoning: model.reasoning,
    input: model.input,
    cost: model.cost,
    contextWindow: model.contextWindow,
    maxTokens: model.maxTokens,
  };
}
