import type { ProfileConfig, RoutingProfile } from "./types.js";

// ---------------------------------------------------------------------------
// Dimension weights (sum ~1.0)
// ---------------------------------------------------------------------------

export const DIMENSION_WEIGHTS = {
  tokenCount: 0.08,
  codePresence: 0.15,
  reasoningMarkers: 0.18,
  technicalTerms: 0.1,
  creativeMarkers: 0.05,
  simpleIndicators: 0.02,
  multiStepPatterns: 0.12,
  questionComplexity: 0.05,
  imperativeVerbs: 0.03,
  constraintCount: 0.04,
  outputFormat: 0.03,
  referenceComplexity: 0.02,
  negationComplexity: 0.01,
  domainSpecificity: 0.02,
  agenticTask: 0.04,
} as const;

// ---------------------------------------------------------------------------
// Tier boundaries (weighted-score thresholds)
// ---------------------------------------------------------------------------

export const TIER_BOUNDARIES = {
  simpleMedium: 0.0,
  mediumComplex: 0.3,
  complexReasoning: 0.5,
} as const;

// ---------------------------------------------------------------------------
// Sigmoid confidence calibration
// ---------------------------------------------------------------------------

export const CONFIDENCE_PARAMS = {
  steepness: 12,
  threshold: 0.7,
} as const;

// ---------------------------------------------------------------------------
// Keyword arrays for 14-dimension scoring
// ---------------------------------------------------------------------------

export const CODE_KEYWORDS = [
  "python",
  "javascript",
  "typescript",
  "java",
  "rust",
  "golang",
  "ruby",
  "php",
  "swift",
  "kotlin",
  "scala",
  "haskell",
  "elixir",
  "c\\+\\+",
  "c#",
  "function",
  "class",
  "method",
  "variable",
  "array",
  "object",
  "loop",
  "recursion",
  "algorithm",
  "data structure",
  "api",
  "endpoint",
  "database",
  "sql",
  "query",
  "schema",
  "migration",
  "compile",
  "build",
  "deploy",
  "debug",
  "test",
  "lint",
  "import",
  "export",
  "module",
  "package",
  "dependency",
  "git",
  "docker",
  "kubernetes",
  "container",
  "pipeline",
  "regex",
  "parse",
  "serialize",
  "async",
  "await",
  "promise",
  "callback",
  "thread",
  "mutex",
  "interface",
  "type",
  "generic",
  "enum",
  "struct",
  "http",
  "rest",
  "graphql",
  "websocket",
  "grpc",
  "npm",
  "pip",
  "cargo",
  "```",
  "def ",
  "fn ",
  "func ",
  "const ",
  "let ",
  "var ",
] as const;

export const REASONING_KEYWORDS = [
  "analyze",
  "evaluate",
  "compare",
  "contrast",
  "explain why",
  "reason",
  "deduce",
  "infer",
  "conclude",
  "prove",
  "derive",
  "justify",
  "argue",
  "critique",
  "assess",
  "synthesize",
  "hypothesize",
  "consider",
  "implications",
  "trade-off",
  "tradeoff",
  "pros and cons",
  "advantages",
  "disadvantages",
  "because",
  "therefore",
  "consequently",
  "furthermore",
  "however",
  "nevertheless",
  "on the other hand",
  "in contrast",
  "step by step",
  "think through",
  "break down",
  "walk me through",
  "what would happen if",
  "why does",
  "how does",
  "what causes",
  "\u5206\u6790",
  "\u8bc4\u4f30",
  "\u63a8\u7406",
  "\u8bc1\u660e",
  "\u89e3\u91ca\u4e3a\u4ec0\u4e48",
  "\u5206\u6790\u3057\u3066",
  "\u8a55\u4fa1\u3057\u3066",
  "\u306a\u305c",
  "\u0430\u043d\u0430\u043b\u0438\u0437\u0438\u0440\u043e\u0432\u0430\u0442\u044c",
  "\u043e\u0446\u0435\u043d\u0438\u0442\u044c",
  "\u043e\u0431\u044a\u044f\u0441\u043d\u0438\u0442\u044c \u043f\u043e\u0447\u0435\u043c\u0443",
  "analysieren",
  "bewerten",
  "erkl\u00e4ren warum",
] as const;

export const CREATIVE_KEYWORDS = [
  "write a story",
  "poem",
  "creative",
  "imagine",
  "fiction",
  "narrative",
  "character",
  "dialogue",
  "scene",
  "plot",
  "metaphor",
  "lyric",
  "compose",
  "brainstorm",
  "ideate",
  "invent",
  "design",
  "artistic",
  "aesthetic",
  "style",
  "tone",
  "voice",
  "mood",
  "atmosphere",
  "vivid",
  "evocative",
] as const;

export const SIMPLE_KEYWORDS = [
  "hi",
  "hello",
  "hey",
  "thanks",
  "thank you",
  "ok",
  "okay",
  "yes",
  "no",
  "sure",
  "bye",
  "goodbye",
  "what time",
  "what date",
  "what day",
  "how are you",
  "who are you",
  "what is your name",
  "good morning",
  "good night",
  "good evening",
  "good afternoon",
  "\u4f60\u597d",
  "\u8c22\u8c22",
  "\u518d\u89c1",
  "\u3053\u3093\u306b\u3061\u306f",
  "\u3042\u308a\u304c\u3068\u3046",
  "\u043f\u0440\u0438\u0432\u0435\u0442",
  "\u0441\u043f\u0430\u0441\u0438\u0431\u043e",
  "hallo",
  "danke",
  "tsch\u00fcss",
] as const;

export const MULTI_STEP_KEYWORDS = [
  "first",
  "then",
  "next",
  "after that",
  "finally",
  "step 1",
  "step 2",
  "step 3",
  "phase",
  "stage",
  "sequence",
  "workflow",
  "pipeline",
  "process",
  "followed by",
  "subsequently",
  "in order to",
  "begin by",
  "start with",
  "proceed to",
  "once done",
  "after completing",
  "the following steps",
  "multi-step",
  "multi-part",
  "series of",
  "chain of",
  "1.",
  "2.",
  "3.",
  "1)",
  "2)",
  "3)",
] as const;

export const TECHNICAL_KEYWORDS = [
  "architecture",
  "infrastructure",
  "scalability",
  "latency",
  "throughput",
  "bandwidth",
  "protocol",
  "encryption",
  "authentication",
  "authorization",
  "middleware",
  "microservice",
  "monolith",
  "distributed",
  "consensus",
  "replication",
  "sharding",
  "load balancing",
  "caching",
  "indexing",
  "normalization",
  "denormalization",
  "deadlock",
  "race condition",
  "concurrency",
  "parallelism",
  "virtualization",
  "containerization",
  "orchestration",
  "observability",
  "telemetry",
  "monitoring",
  "kernel",
  "syscall",
  "filesystem",
  "memory management",
  "garbage collection",
  "compiler",
  "interpreter",
  "bytecode",
  "jit",
  "aot",
] as const;

export const IMPERATIVE_KEYWORDS = [
  "create",
  "make",
  "build",
  "generate",
  "write",
  "implement",
  "add",
  "remove",
  "delete",
  "update",
  "modify",
  "change",
  "fix",
  "refactor",
  "optimize",
  "convert",
  "transform",
  "extract",
  "merge",
  "split",
  "install",
  "configure",
  "setup",
  "deploy",
  "run",
  "execute",
  "start",
  "stop",
  "restart",
  "reset",
  "clear",
  "clean",
  "format",
  "sort",
  "filter",
  "map",
  "reduce",
  "validate",
  "verify",
  "check",
  "test",
] as const;

export const DOMAIN_KEYWORDS = [
  "stock",
  "bond",
  "portfolio",
  "derivative",
  "hedge",
  "arbitrage",
  "yield",
  "dividend",
  "equity",
  "futures",
  "options",
  "volatility",
  "diagnosis",
  "prognosis",
  "pathology",
  "pharmacology",
  "clinical trial",
  "symptom",
  "treatment",
  "therapy",
  "patient",
  "dosage",
  "statute",
  "precedent",
  "jurisdiction",
  "liability",
  "compliance",
  "regulation",
  "contract",
  "tort",
  "plaintiff",
  "defendant",
  "hypothesis",
  "experiment",
  "control group",
  "statistical",
  "correlation",
  "regression",
  "p-value",
  "confidence interval",
] as const;

export const AGENTIC_KEYWORDS = [
  "read file",
  "read the file",
  "open file",
  "look at",
  "check the",
  "search for",
  "find all",
  "list all",
  "scan",
  "browse",
  "explore",
  "create file",
  "write file",
  "save to",
  "write to",
  "output to",
  "run command",
  "execute command",
  "run script",
  "run the",
  "install package",
  "install dependency",
  "npm install",
  "pip install",
  "call api",
  "make request",
  "fetch",
  "curl",
  "http request",
  "create issue",
  "open pr",
  "pull request",
  "commit",
  "push",
  "search codebase",
  "grep",
  "find in",
  "look through",
  "for each",
  "iterate",
  "batch",
  "process all",
  "handle each",
  "use tool",
  "invoke",
  "trigger",
  "automate",
  "schedule",
] as const;

export const OUTPUT_FORMAT_MARKERS = [
  "json",
  "xml",
  "yaml",
  "csv",
  "markdown",
  "html",
  "table",
  "list",
  "bullet",
  "numbered",
  "format as",
  "output as",
  "return as",
  "structured",
  "formatted",
  "template",
] as const;

export const CONSTRAINT_MARKERS = [
  "must",
  "must not",
  "should",
  "should not",
  "shall",
  "required",
  "exactly",
  "at most",
  "at least",
  "no more than",
  "no less than",
  "between",
  "within",
  "limit",
  "constraint",
  "restriction",
  "only",
  "except",
  "unless",
  "without",
  "do not",
  "don't",
  "never",
  "always",
  "ensure",
  "make sure",
  "guarantee",
] as const;

export const REFERENCE_MARKERS = [
  "according to",
  "based on",
  "referring to",
  "as mentioned",
  "as described in",
  "from the",
  "per the",
  "following the",
  "in the documentation",
  "in the spec",
  "in the paper",
  "in the article",
  "see also",
  "cross-reference",
  "cf.",
  "ibid",
] as const;

export const NEGATION_MARKERS = [
  "not",
  "don't",
  "doesn't",
  "won't",
  "can't",
  "shouldn't",
  "wouldn't",
  "couldn't",
  "isn't",
  "aren't",
  "wasn't",
  "weren't",
  "haven't",
  "hasn't",
  "hadn't",
  "without",
  "never",
  "neither",
  "nor",
  "none",
  "nobody",
  "nothing",
  "nowhere",
  "no one",
] as const;

// ---------------------------------------------------------------------------
// Profile presets: tier -> model mapping
// ---------------------------------------------------------------------------

export const PROFILES: Record<RoutingProfile, ProfileConfig> = {
  auto: {
    name: "auto",
    label: "Auto",
    description: "Balanced: local for simple, cloud for complex",
    tierModels: {
      SIMPLE: "ollama/gemma3:4b",
      MEDIUM: "google/gemini-2.0-flash",
      COMPLEX: "anthropic/claude-sonnet-4-5",
      REASONING: "anthropic/claude-sonnet-4-5",
    },
  },
  eco: {
    name: "eco",
    label: "Economy",
    description: "Minimize cloud API costs, prefer local models",
    tierModels: {
      SIMPLE: "ollama/gemma3:4b",
      MEDIUM: "ollama/gemma3:4b",
      COMPLEX: "google/gemini-2.0-flash",
      REASONING: "google/gemini-2.0-flash",
    },
  },
  premium: {
    name: "premium",
    label: "Premium",
    description: "Best quality, prefer top-tier cloud models",
    tierModels: {
      SIMPLE: "google/gemini-2.0-flash",
      MEDIUM: "anthropic/claude-sonnet-4-5",
      COMPLEX: "anthropic/claude-sonnet-4-5",
      REASONING: "anthropic/claude-sonnet-4-5",
    },
  },
  free: {
    name: "free",
    label: "Free (Local Only)",
    description: "All requests routed to local Ollama models",
    tierModels: {
      SIMPLE: "ollama/gemma3:4b",
      MEDIUM: "ollama/gemma3:4b",
      COMPLEX: "ollama/gemma3:4b",
      REASONING: "ollama/gemma3:4b",
    },
  },
};

// ---------------------------------------------------------------------------
// Default provider endpoints (overridden by openclaw config when available)
// ---------------------------------------------------------------------------

export const DEFAULT_PROVIDER_URLS: Record<string, string> = {
  ollama: "http://127.0.0.1:11434/v1",
  openai: "https://api.openai.com/v1",
  anthropic: "https://api.anthropic.com",
  google: "https://generativelanguage.googleapis.com/v1beta/openai",
  groq: "https://api.groq.com/openai/v1",
};

export const PROVIDER_ENV_VARS: Record<string, string> = {
  anthropic: "ANTHROPIC_API_KEY",
  openai: "OPENAI_API_KEY",
  google: "GOOGLE_API_KEY",
  groq: "GROQ_API_KEY",
};

export const SERVER_PORT = 18792;
export const SERVER_HOST = "127.0.0.1";
