#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Native macOS/iOS Apps

set -e

echo "========================================"
echo "Native Apps Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check for Xcode
echo "Checking for Xcode..."
if ! command -v xcodegen &> /dev/null; then
    echo -e "${YELLOW}XcodeGen not found. Installing via Homebrew...${NC}"
    if command -v brew &> /dev/null; then
        brew install xcodegen
    else
        echo -e "${RED}Homebrew not found. Please install XcodeGen manually.${NC}"
        exit 1
    fi
fi

echo -e "${GREEN}XcodeGen is available${NC}"

# Check for Xcode (GUI)
if [ -d "/Applications/Xcode.app" ]; then
    echo -e "${GREEN}Xcode is installed${NC}"
else
    echo -e "${YELLOW}Xcode not found in Applications. Please install Xcode from App Store.${NC}"
fi

# Verify Xcode projects exist
echo ""
echo "Verifying Xcode projects..."

if [ -d "macos/OpenClaw.xcodeproj" ]; then
    echo -e "${GREEN}macOS project found: macos/OpenClaw.xcodeproj${NC}"
else
    echo -e "${YELLOW}macOS project not found. Running xcodegen...${NC}"
    cd macos && xcodegen generate && cd ..
fi

if [ -d "ios/OpenClaw.xcodeproj" ]; then
    echo -e "${GREEN}iOS project found: ios/OpenClaw.xcodeproj${NC}"
else
    echo -e "${YELLOW}iOS project not found. Running xcodegen...${NC}"
    cd ios && xcodegen generate && cd ..
fi

# ============================================
# DEVELOPMENT INSTRUCTIONS
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "To develop and build the native apps:"
echo ""
echo "1. Open macOS project in Xcode:"
echo "   open macos/OpenClaw.xcodeproj"
echo ""
echo "2. Open iOS project in Xcode:"
echo "   open ios/OpenClaw.xcodeproj"
echo ""
echo "3. Build from command line:"
echo "   # macOS"
echo "   xcodebuild -project macos/OpenClaw.xcodeproj -scheme OpenClaw -configuration Debug build"
echo ""
echo "   # iOS"
echo "   xcodebuild -project ios/OpenClaw.xcodeproj -scheme OpenClaw -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15' build"
echo ""
echo "4. Run tests:"
echo "   # macOS"
echo "   xcodebuild -project macos/OpenClaw.xcodeproj -scheme OpenClaw -configuration Debug test"
echo ""
echo "   # iOS"
echo "   xcodebuild -project ios/OpenClaw.xcodeproj -scheme OpenClaw -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15' test"
echo ""

echo "Note: This project uses SwiftUI materials and NSVisualEffectView for glassmorphism."
echo "      The design system requires macOS 12+ and iOS 15+ for full compatibility."
