#!/bin/bash
# review-staging.sh - Generate diff summary for staged files
#
# Usage: ./review-staging.sh [filename]
# If no filename provided, reviews all staged files
#
# This script helps the Supervisor agent by providing a structured
# diff that's easier to analyze than raw diff output.

set -e

STAGING_DIR="$HOME/clawd/.staging"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Function to get target path for a file
get_target_path() {
    local file="$1"
    case "$file" in
        moltbot.json) echo "$HOME/.clawdbot/moltbot.json" ;;
        jobs.json) echo "$HOME/.clawdbot/cron/jobs.json" ;;
        SOUL.md|IDENTITY.md|STATUS.md|AGENTS.md) echo "$HOME/clawd/$file" ;;
        *) echo "$HOME/.clawdbot/$file" ;;
    esac
}

# Function to review a single staged file
review_file() {
    local staged="$1"
    local filename=$(basename "$staged" .proposed)
    local target=$(get_target_path "$filename")
    local review_file="$STAGING_DIR/$filename.review.md"
    
    echo -e "${BLUE}Reviewing: $filename${NC}"
    
    if [ ! -f "$target" ]; then
        echo -e "${RED}Error: Target file not found: $target${NC}"
        return 1
    fi
    
    # Generate review document
    cat > "$review_file" << EOF
# Staging Review: $filename

**Generated by:** review-staging.sh (for Supervisor)
**Date:** $(date -u +"%Y-%m-%d %H:%M UTC")
**Original:** $target
**Proposed:** $staged

## Diff Summary

\`\`\`diff
$(diff -u "$target" "$staged" 2>/dev/null || true)
\`\`\`

## Statistics

- Original lines: $(wc -l < "$target")
- Proposed lines: $(wc -l < "$staged")
- Lines added: $(diff "$target" "$staged" 2>/dev/null | grep "^>" | wc -l)
- Lines removed: $(diff "$target" "$staged" 2>/dev/null | grep "^<" | wc -l)

## For Supervisor Review

Please analyze the diff above and provide:
1. Summary of what Liam is trying to accomplish
2. Security review (secrets, permissions, scope)
3. Recommendation (APPROVE / REVIEW CAREFULLY / REJECT)

## For Simon

To apply: \`~/clawd/scripts/apply-staging.sh $filename\`
To reject: \`rm $staged\`
To see this review: \`cat $review_file\`
EOF

    echo -e "${GREEN}Review generated: $review_file${NC}"
    echo ""
    
    # Also print summary to stdout
    echo -e "${YELLOW}=== Quick Summary ===${NC}"
    echo "File: $filename"
    echo "Lines changed: +$(diff "$target" "$staged" 2>/dev/null | grep "^>" | wc -l) / -$(diff "$target" "$staged" 2>/dev/null | grep "^<" | wc -l)"
    echo "Review file: $review_file"
    echo ""
}

# Main logic
if [ -n "$1" ]; then
    # Review specific file
    staged="$STAGING_DIR/$1.proposed"
    if [ ! -f "$staged" ]; then
        echo -e "${RED}No staged file found: $staged${NC}"
        exit 1
    fi
    review_file "$staged"
else
    # Review all staged files
    echo -e "${BLUE}=== Staged Files Review ===${NC}"
    echo ""
    
    staged_files=$(find "$STAGING_DIR" -name "*.proposed" 2>/dev/null)
    
    if [ -z "$staged_files" ]; then
        echo -e "${GREEN}No staged files pending review.${NC}"
        exit 0
    fi
    
    for staged in $staged_files; do
        review_file "$staged"
    done
    
    echo -e "${BLUE}=== Summary ===${NC}"
    echo "Total staged files: $(echo "$staged_files" | wc -w)"
    echo "Review files generated in: $STAGING_DIR/*.review.md"
fi
