$body = @'
<ENVELOPE>
<HEADER><VERSION>1</VERSION><TALLYREQUEST>Import</TALLYREQUEST><TYPE>Data</TYPE><ID>All Masters</ID></HEADER>
<BODY><DESC>
<STATICVARIABLES>
<SVCURRENTCOMPANY>PAVISHA PET INDUSTRIES</SVCURRENTCOMPANY>
</STATICVARIABLES>
</DESC>
<DATA>
<TALLYMESSAGE>
<VOUCHER VCHTYPE="Stock Journal" ACTION="Create">
<DATE>20260215</DATE>
<EFFECTIVEDATE>20260215</EFFECTIVEDATE>
<VOUCHERTYPENAME>Stock Journal</VOUCHERTYPENAME>
<NARRATION>TEST - DELETE ME</NARRATION>
<INVENTORYENTRIESIN.LIST>
 <STOCKITEMNAME>19gm Pet Jar</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <RATE>0/pc</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY>1 pc</ACTUALQTY>
 <BILLEDQTY>1 pc</BILLEDQTY>
</INVENTORYENTRIESIN.LIST>
<INVENTORYENTRIESOUT.LIST>
 <STOCKITEMNAME>ASPET AS 20C PET RESIN</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <RATE>0/kg</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY>0.019 kg</ACTUALQTY>
 <BILLEDQTY>0.019 kg</BILLEDQTY>
</INVENTORYENTRIESOUT.LIST>
</VOUCHER>
</TALLYMESSAGE>
</DATA>
</BODY>
</ENVELOPE>
'@
$r = Invoke-WebRequest -Uri 'http://localhost:9000' -Method Post -Body $body -TimeoutSec 30 -UseBasicParsing
$r.Content
