$body = @'
<ENVELOPE>
<HEADER><VERSION>1</VERSION><TALLYREQUEST>Import</TALLYREQUEST><TYPE>Data</TYPE><ID>All Masters</ID></HEADER>
<BODY><DESC>
<STATICVARIABLES>
<SVCURRENTCOMPANY>PAVISHA POLYMERS</SVCURRENTCOMPANY>
</STATICVARIABLES>
</DESC>
<DATA>
<TALLYMESSAGE>
<VOUCHER VCHTYPE="Manufacturing Journal" ACTION="Create">
<DATE>20260215</DATE>
<VOUCHERTYPENAME>Manufacturing Journal</VOUCHERTYPENAME>
<NARRATION>Test MFG - Invoice #43 Arun Book Depo</NARRATION>
<INVENTORYENTRIESIN.LIST>
 <STOCKITEMNAME>47gm. 1lt. Pet Bottle</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <RATE> 0/pc</RATE>
 <AMOUNT> 0</AMOUNT>
 <ACTUALQTY> 2016 pc</ACTUALQTY>
 <BILLEDQTY> 2016 pc</BILLEDQTY>
</INVENTORYENTRIESIN.LIST>
<INVENTORYENTRIESIN.LIST>
 <STOCKITEMNAME>45gm. Pet Bottle+Flip Top Cap</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <RATE> 0/pc</RATE>
 <AMOUNT> 0</AMOUNT>
 <ACTUALQTY> 720 pc</ACTUALQTY>
 <BILLEDQTY> 720 pc</BILLEDQTY>
</INVENTORYENTRIESIN.LIST>
<INVENTORYENTRIESOUT.LIST>
 <STOCKITEMNAME>PET PREFORMS</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <RATE> 0/kg</RATE>
 <AMOUNT> 0</AMOUNT>
 <ACTUALQTY> 127.152 kg</ACTUALQTY>
 <BILLEDQTY> 127.152 kg</BILLEDQTY>
</INVENTORYENTRIESOUT.LIST>
<INVENTORYENTRIESOUT.LIST>
 <STOCKITEMNAME>Cap 46mm Flip Top</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <RATE> 0/pc</RATE>
 <AMOUNT> 0</AMOUNT>
 <ACTUALQTY> 720 pc</ACTUALQTY>
 <BILLEDQTY> 720 pc</BILLEDQTY>
</INVENTORYENTRIESOUT.LIST>
</VOUCHER>
</TALLYMESSAGE>
</DATA>
</BODY>
</ENVELOPE>
'@
$r = Invoke-WebRequest -Uri 'http://localhost:9000' -Method Post -Body $body -TimeoutSec 30 -UseBasicParsing
$r.Content
