$body = @'
<ENVELOPE>
<HEADER><VERSION>1</VERSION><TALLYREQUEST>Export</TALLYREQUEST><TYPE>Collection</TYPE><ID>BOMCheck</ID></HEADER>
<BODY><DESC>
<STATICVARIABLES>
<SVCURRENTCOMPANY>PAVISHA POLYMERS</SVCURRENTCOMPANY>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
</STATICVARIABLES>
<TDL><TDLMESSAGE>
<COLLECTION NAME="BOMCheck" ISMODIFY="No">
<TYPE>StockItem</TYPE>
<CHILDOF>Finish Products</CHILDOF>
<FETCH>NAME, BOMNAME, COMPONENTLIST.LIST, EXTCOMPONENTLIST.LIST, BOMDETAILS.LIST</FETCH>
<FILTER>NameFilter</FILTER>
</COLLECTION>
<SYSTEM TYPE="Formulae" NAME="NameFilter">$Name = "47gm. 1lt. Pet Bottle"</SYSTEM>
</TDLMESSAGE></TDL>
</DESC></BODY>
</ENVELOPE>
'@
$r = Invoke-WebRequest -Uri 'http://localhost:9000' -Method Post -Body $body -TimeoutSec 15 -UseBasicParsing
$r.Content
