import urllib.request

# Alter Manufacturing Journal #36 (Invoice #43) to add rates
# GUID: f8af189b-2cad-4150-a871-59d374eb68b9-00002756
# Rates: PET PREFORMS ₹120.15/kg, Cap 46mm Flip Top ₹2.82/pc

# Calculations:
# PET PREFORMS: 127.152 kg * 120.15 = 15,277.17
# Cap 46mm Flip Top: 720 * 2.82 = 2,030.40
# 47gm bottle 2016pc: raw cost = 94.752kg * 120.15 = 11,384.47
# 45gm flip top 720pc: raw cost = 32.4kg * 120.15 + 720 * 2.82 = 3,892.86 + 2,030.40 = 5,923.26
# Total raw = 15,277.33 (rounding) -- let's use exact: 127152gm = 127.152kg

pet_preform_rate = 120.15  # per kg
cap_flip_rate = 2.82       # per pc

# Raw material amounts (consumed = positive in Tally MFG journal OUT entries)
pet_qty_kg = 127.152
pet_amount = round(pet_qty_kg * pet_preform_rate, 2)  # 15277.17

cap_qty = 720
cap_amount = round(cap_qty * cap_flip_rate, 2)  # 2030.40

# Finished goods amounts (produced = negative in Tally MFG journal IN entries)
bottle_qty = 2016
bottle_cost_per_pc = (47/1000) * pet_preform_rate  # 5.6471
bottle_amount = round(bottle_qty * bottle_cost_per_pc, 2)  # 11384.47

fliptop_qty = 720
fliptop_cost_per_pc = (45/1000) * pet_preform_rate + cap_flip_rate  # 8.2268
fliptop_amount = round(fliptop_qty * fliptop_cost_per_pc, 2)  # 5923.26

print(f"PET PREFORMS: {pet_qty_kg}kg x {pet_preform_rate} = {pet_amount}")
print(f"Cap 46mm: {cap_qty}pc x {cap_flip_rate} = {cap_amount}")
print(f"47gm bottle: {bottle_qty}pc @ {bottle_cost_per_pc:.4f} = {bottle_amount}")
print(f"45gm flip top: {fliptop_qty}pc @ {fliptop_cost_per_pc:.4f} = {fliptop_amount}")
print(f"Total IN: {bottle_amount + fliptop_amount}")
print(f"Total OUT: {pet_amount + cap_amount}")

xml = f'''<ENVELOPE>
<HEADER><VERSION>1</VERSION><TALLYREQUEST>Import</TALLYREQUEST><TYPE>Data</TYPE><ID>Vouchers</ID></HEADER>
<BODY><DESC>
<STATICVARIABLES>
<SVCURRENTCOMPANY>PAVISHA POLYMERS</SVCURRENTCOMPANY>
</STATICVARIABLES>
</DESC>
<DATA>
<TALLYMESSAGE>
<VOUCHER VCHTYPE="Manufacturing Journal" ACTION="Alter" OBJVIEW="Multi Consumption Voucher View" REMOTEID="f8af189b-2cad-4150-a871-59d374eb68b9-00002756">
<DATE>20250701</DATE>
<EFFECTIVEDATE>20250701</EFFECTIVEDATE>
<VOUCHERTYPENAME>Manufacturing Journal</VOUCHERTYPENAME>
<NARRATION>Manufacturing for Sale Invoice #43 dated 23-Jul-25 (Arun Book Depo)</NARRATION>
<DESTINATIONGODOWN>Main Location</DESTINATIONGODOWN>
<VOUCHERDESTINATIONGODOWN>Main Location</VOUCHERDESTINATIONGODOWN>
<VOUCHERSOURCEGODOWN>Main Location</VOUCHERSOURCEGODOWN>
<FORJOBCOSTING>Yes</FORJOBCOSTING>
<VCHPROPISSTKJRNL>Yes</VCHPROPISSTKJRNL>
<ISNEGISPOSSET>Yes</ISNEGISPOSSET>
<ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
<DIFFACTUALQTY>No</DIFFACTUALQTY>

<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>47gm. 1lt. Pet Bottle</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>{bottle_cost_per_pc:.4f}/pc</RATE>
 <AMOUNT>-{bottle_amount}</AMOUNT>
 <ACTUALQTY> 2016 pc</ACTUALQTY>
 <BILLEDQTY> 2016 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>-{bottle_amount}</AMOUNT>
  <ACTUALQTY> 2016 pc</ACTUALQTY>
  <BILLEDQTY> 2016 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>

<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>45gm. Pet Bottle+Flip Top Cap</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>{fliptop_cost_per_pc:.4f}/pc</RATE>
 <AMOUNT>-{fliptop_amount}</AMOUNT>
 <ACTUALQTY> 720 pc</ACTUALQTY>
 <BILLEDQTY> 720 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>-{fliptop_amount}</AMOUNT>
  <ACTUALQTY> 720 pc</ACTUALQTY>
  <BILLEDQTY> 720 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>

<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>PET PREFORMS</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>{pet_preform_rate}/kg</RATE>
 <AMOUNT>{pet_amount}</AMOUNT>
 <ACTUALQTY> 127 kg 152 gm.</ACTUALQTY>
 <BILLEDQTY> 127 kg 152 gm.</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>{pet_amount}</AMOUNT>
  <ACTUALQTY> 127 kg 152 gm.</ACTUALQTY>
  <BILLEDQTY> 127 kg 152 gm.</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>

<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>Cap 46mm Flip Top</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>{cap_flip_rate}/pc</RATE>
 <AMOUNT>{cap_amount}</AMOUNT>
 <ACTUALQTY> 720 pc</ACTUALQTY>
 <BILLEDQTY> 720 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>{cap_amount}</AMOUNT>
  <ACTUALQTY> 720 pc</ACTUALQTY>
  <BILLEDQTY> 720 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>

<INVENTORYENTRIESIN.LIST>
 <STOCKITEMNAME>47gm. 1lt. Pet Bottle</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>{bottle_cost_per_pc:.4f}/pc</RATE>
 <AMOUNT>-{bottle_amount}</AMOUNT>
 <ACTUALQTY> 2016 pc</ACTUALQTY>
 <BILLEDQTY> 2016 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>-{bottle_amount}</AMOUNT>
  <ACTUALQTY> 2016 pc</ACTUALQTY>
  <BILLEDQTY> 2016 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESIN.LIST>

<INVENTORYENTRIESIN.LIST>
 <STOCKITEMNAME>45gm. Pet Bottle+Flip Top Cap</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>{fliptop_cost_per_pc:.4f}/pc</RATE>
 <AMOUNT>-{fliptop_amount}</AMOUNT>
 <ACTUALQTY> 720 pc</ACTUALQTY>
 <BILLEDQTY> 720 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>-{fliptop_amount}</AMOUNT>
  <ACTUALQTY> 720 pc</ACTUALQTY>
  <BILLEDQTY> 720 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESIN.LIST>

<INVENTORYENTRIESOUT.LIST>
 <STOCKITEMNAME>PET PREFORMS</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>{pet_preform_rate}/kg</RATE>
 <AMOUNT>{pet_amount}</AMOUNT>
 <ACTUALQTY> 127 kg 152 gm.</ACTUALQTY>
 <BILLEDQTY> 127 kg 152 gm.</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>{pet_amount}</AMOUNT>
  <ACTUALQTY> 127 kg 152 gm.</ACTUALQTY>
  <BILLEDQTY> 127 kg 152 gm.</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESOUT.LIST>

<INVENTORYENTRIESOUT.LIST>
 <STOCKITEMNAME>Cap 46mm Flip Top</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>{cap_flip_rate}/pc</RATE>
 <AMOUNT>{cap_amount}</AMOUNT>
 <ACTUALQTY> 720 pc</ACTUALQTY>
 <BILLEDQTY> 720 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>{cap_amount}</AMOUNT>
  <ACTUALQTY> 720 pc</ACTUALQTY>
  <BILLEDQTY> 720 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESOUT.LIST>

</VOUCHER>
</TALLYMESSAGE>
</DATA>
</BODY>
</ENVELOPE>'''

req = urllib.request.Request('http://localhost:9000', data=xml.encode('utf-8'), method='POST')
req.add_header('Content-Type', 'text/xml; charset=utf-8')
try:
    resp = urllib.request.urlopen(req, timeout=30)
    print(resp.read().decode('utf-8'))
except Exception as e:
    print(f"Error: {e}")
