import urllib.request

def try_hack(hack_name, static_vars, date="20250722"):
    xml = f'''<ENVELOPE>
<HEADER><VERSION>1</VERSION><TALLYREQUEST>Import</TALLYREQUEST><TYPE>Data</TYPE><ID>Vouchers</ID></HEADER>
<BODY><DESC>
<STATICVARIABLES>
<SVCURRENTCOMPANY>PAVISHA POLYMERS</SVCURRENTCOMPANY>
{static_vars}
</STATICVARIABLES>
</DESC>
<DATA>
<TALLYMESSAGE>
<VOUCHER VCHTYPE="Manufacturing Journal" ACTION="Create" OBJVIEW="Multi Consumption Voucher View">
<DATE>{date}</DATE>
<EFFECTIVEDATE>{date}</EFFECTIVEDATE>
<VOUCHERTYPENAME>Manufacturing Journal</VOUCHERTYPENAME>
<NARRATION>HACK TEST {hack_name} - DELETE ME</NARRATION>
<DESTINATIONGODOWN>Main Location</DESTINATIONGODOWN>
<VOUCHERDESTINATIONGODOWN>Main Location</VOUCHERDESTINATIONGODOWN>
<VOUCHERSOURCEGODOWN>Main Location</VOUCHERSOURCEGODOWN>
<FORJOBCOSTING>Yes</FORJOBCOSTING>
<VCHPROPISSTKJRNL>Yes</VCHPROPISSTKJRNL>
<ISNEGISPOSSET>Yes</ISNEGISPOSSET>
<ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
<DIFFACTUALQTY>No</DIFFACTUALQTY>
<NUMBERINGSTYLE>Auto Renumber</NUMBERINGSTYLE>
<VOUCHERNUMBERSERIES>Default</VOUCHERNUMBERSERIES>
<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>47gm. 1lt. Pet Bottle</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE><AMOUNT>0</AMOUNT>
 <ACTUALQTY> 1 pc</ACTUALQTY><BILLEDQTY> 1 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST><BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT><ACTUALQTY> 1 pc</ACTUALQTY><BILLEDQTY> 1 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>
<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>PET PREFORMS</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>0/kg</RATE><AMOUNT>0</AMOUNT>
 <ACTUALQTY> 0 kg 47 gm.</ACTUALQTY><BILLEDQTY> 0 kg 47 gm.</BILLEDQTY>
 <BATCHALLOCATIONS.LIST><GODOWNNAME>Main Location</GODOWNNAME><BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT><ACTUALQTY> 0 kg 47 gm.</ACTUALQTY><BILLEDQTY> 0 kg 47 gm.</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>
<INVENTORYENTRIESIN.LIST>
 <STOCKITEMNAME>47gm. 1lt. Pet Bottle</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE><AMOUNT>0</AMOUNT>
 <ACTUALQTY> 1 pc</ACTUALQTY><BILLEDQTY> 1 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST><GODOWNNAME>Main Location</GODOWNNAME><BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT><ACTUALQTY> 1 pc</ACTUALQTY><BILLEDQTY> 1 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESIN.LIST>
<INVENTORYENTRIESOUT.LIST>
 <STOCKITEMNAME>PET PREFORMS</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>0/kg</RATE><AMOUNT>0</AMOUNT>
 <ACTUALQTY> 0 kg 47 gm.</ACTUALQTY><BILLEDQTY> 0 kg 47 gm.</BILLEDQTY>
 <BATCHALLOCATIONS.LIST><GODOWNNAME>Main Location</GODOWNNAME><BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT><ACTUALQTY> 0 kg 47 gm.</ACTUALQTY><BILLEDQTY> 0 kg 47 gm.</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESOUT.LIST>
</VOUCHER>
</TALLYMESSAGE>
</DATA>
</BODY>
</ENVELOPE>'''
    req = urllib.request.Request('http://localhost:9000', data=xml.encode('utf-8'), method='POST')
    req.add_header('Content-Type', 'text/xml; charset=utf-8')
    resp = urllib.request.urlopen(req, timeout=30)
    result = resp.read().decode('utf-8')
    ok = '<CREATED>1</CREATED>' in result
    print(f"  {hack_name}: {'SUCCESS' if ok else 'FAILED'}")
    return ok

# Hack 1: Set SVCURRENTDATE to match voucher date
try_hack("SVCURRENTDATE", "<SVCURRENTDATE>20250722</SVCURRENTDATE>")

# Hack 2: Set SVFROMDATE/SVTODATE 
try_hack("SVFROMDATE+SVTODATE", "<SVFROMDATE>20250401</SVFROMDATE><SVTODATE>20260331</SVTODATE>")

# Hack 3: Both SVCURRENTDATE + SVFROMDATE/SVTODATE
try_hack("ALL_SV", "<SVCURRENTDATE>20250722</SVCURRENTDATE><SVFROMDATE>20250401</SVFROMDATE><SVTODATE>20260331</SVTODATE>")

# Hack 4: SVCURRENTDATE + date on 2nd of month
try_hack("SVCURRENTDATE_2nd", "<SVCURRENTDATE>20250702</SVCURRENTDATE>", date="20250702")

# Hack 5: Try date 20250702 without any SV hacks
try_hack("Plain_2nd", "", date="20250702")
