$body = @'
<ENVELOPE>
<HEADER><VERSION>1</VERSION><TALLYREQUEST>Export</TALLYREQUEST><TYPE>Collection</TYPE><ID>CompFeatures</ID></HEADER>
<BODY><DESC>
<STATICVARIABLES>
<SVCURRENTCOMPANY>PAVISHA POLYMERS</SVCURRENTCOMPANY>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
</STATICVARIABLES>
<TDL><TDLMESSAGE>
<COLLECTION NAME="CompFeatures" ISMODIFY="No">
<TYPE>Company</TYPE>
<FETCH>USEMANUFJOURNAL, ISBILLOFMATERIALSENABLED, ISUSEALIASFORSTOCKITEM, ISMAINTAINBILLOFMATERIALS, HASBOM, USEALIASFORSTOCKITEM, ISINVENTORYON, ISINTEGRATEACCWITHSTOCK, ISUSEALIASFORSTOCKGROUP, ISUSEMULTIPLEGODWNS, ISUSETRACKING, ISUSEORDERSPROCESSING, ISUSEJOBCOSTING, ISUSEADDALLOCATIONFORSTOCKJOURNAL, ISUSEEXPIRYDATE, ISUSEBATCH, ISDIFFERENTACTUALANDBILEDQTY, ISUSECOMPONENTLIST</FETCH>
</COLLECTION>
</TDLMESSAGE></TDL>
</DESC></BODY>
</ENVELOPE>
'@
$r = Invoke-WebRequest -Uri 'http://localhost:9000' -Method Post -Body $body -TimeoutSec 15 -UseBasicParsing
$r.Content
