import urllib.request

def test_date(date_str):
    xml = f'''<ENVELOPE>
<HEADER><VERSION>1</VERSION><TALLYREQUEST>Import</TALLYREQUEST><TYPE>Data</TYPE><ID>Vouchers</ID></HEADER>
<BODY><DESC>
<STATICVARIABLES><SVCURRENTCOMPANY>PAVISHA POLYMERS</SVCURRENTCOMPANY></STATICVARIABLES>
</DESC>
<DATA><TALLYMESSAGE>
<VOUCHER VCHTYPE="Manufacturing Journal" ACTION="Create" OBJVIEW="Multi Consumption Voucher View">
<DATE>{date_str}</DATE><EFFECTIVEDATE>{date_str}</EFFECTIVEDATE>
<VOUCHERTYPENAME>Manufacturing Journal</VOUCHERTYPENAME>
<NARRATION>DATERANGE TEST</NARRATION>
<DESTINATIONGODOWN>Main Location</DESTINATIONGODOWN>
<VOUCHERDESTINATIONGODOWN>Main Location</VOUCHERDESTINATIONGODOWN>
<VOUCHERSOURCEGODOWN>Main Location</VOUCHERSOURCEGODOWN>
<FORJOBCOSTING>Yes</FORJOBCOSTING><VCHPROPISSTKJRNL>Yes</VCHPROPISSTKJRNL>
<ISNEGISPOSSET>Yes</ISNEGISPOSSET><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
<DIFFACTUALQTY>No</DIFFACTUALQTY>
<NUMBERINGSTYLE>Auto Renumber</NUMBERINGSTYLE><VOUCHERNUMBERSERIES>Default</VOUCHERNUMBERSERIES>
<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>47gm. 1lt. Pet Bottle</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE><AMOUNT>0</AMOUNT><ACTUALQTY> 1 pc</ACTUALQTY><BILLEDQTY> 1 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST><BATCHNAME>Primary Batch</BATCHNAME><AMOUNT>0</AMOUNT><ACTUALQTY> 1 pc</ACTUALQTY><BILLEDQTY> 1 pc</BILLEDQTY></BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>
<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>PET PREFORMS</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>0/kg</RATE><AMOUNT>0</AMOUNT><ACTUALQTY> 0 kg 47 gm.</ACTUALQTY><BILLEDQTY> 0 kg 47 gm.</BILLEDQTY>
 <BATCHALLOCATIONS.LIST><GODOWNNAME>Main Location</GODOWNNAME><BATCHNAME>Primary Batch</BATCHNAME><AMOUNT>0</AMOUNT><ACTUALQTY> 0 kg 47 gm.</ACTUALQTY><BILLEDQTY> 0 kg 47 gm.</BILLEDQTY></BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>
<INVENTORYENTRIESIN.LIST>
 <STOCKITEMNAME>47gm. 1lt. Pet Bottle</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE><AMOUNT>0</AMOUNT><ACTUALQTY> 1 pc</ACTUALQTY><BILLEDQTY> 1 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST><GODOWNNAME>Main Location</GODOWNNAME><BATCHNAME>Primary Batch</BATCHNAME><AMOUNT>0</AMOUNT><ACTUALQTY> 1 pc</ACTUALQTY><BILLEDQTY> 1 pc</BILLEDQTY></BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESIN.LIST>
<INVENTORYENTRIESOUT.LIST>
 <STOCKITEMNAME>PET PREFORMS</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>0/kg</RATE><AMOUNT>0</AMOUNT><ACTUALQTY> 0 kg 47 gm.</ACTUALQTY><BILLEDQTY> 0 kg 47 gm.</BILLEDQTY>
 <BATCHALLOCATIONS.LIST><GODOWNNAME>Main Location</GODOWNNAME><BATCHNAME>Primary Batch</BATCHNAME><AMOUNT>0</AMOUNT><ACTUALQTY> 0 kg 47 gm.</ACTUALQTY><BILLEDQTY> 0 kg 47 gm.</BILLEDQTY></BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESOUT.LIST>
</VOUCHER>
</TALLYMESSAGE></DATA></BODY></ENVELOPE>'''
    req = urllib.request.Request('http://localhost:9000', data=xml.encode('utf-8'), method='POST')
    req.add_header('Content-Type', 'text/xml; charset=utf-8')
    resp = urllib.request.urlopen(req, timeout=30)
    return '<CREATED>1</CREATED>' in resp.read().decode('utf-8')

# Test every day of July 2025
print("=== July 2025 ===")
results = []
for day in range(1, 32):
    ds = f"202507{day:02d}"
    ok = test_date(ds)
    results.append((day, ok))
    
for day, ok in results:
    print(f"  Jul {day:2d}: {'OK' if ok else 'FAIL'}")
