$body = @'
<ENVELOPE>
<HEADER><VERSION>1</VERSION><TALLYREQUEST>Import</TALLYREQUEST><TYPE>Data</TYPE><ID>All Masters</ID></HEADER>
<BODY><DESC>
<STATICVARIABLES>
<SVCURRENTCOMPANY>PAVISHA POLYMERS</SVCURRENTCOMPANY>
</STATICVARIABLES>
</DESC>
<DATA>
<TALLYMESSAGE>
<VOUCHER VCHTYPE="Manufacturing Journal" ACTION="Create" OBJVIEW="Multi Consumption Voucher View">
<DATE>20260215</DATE>
<EFFECTIVEDATE>20260215</EFFECTIVEDATE>
<VOUCHERTYPENAME>Manufacturing Journal</VOUCHERTYPENAME>
<NARRATION>Test MFG - Invoice #43</NARRATION>
<DESTINATIONGODOWN>Main Location</DESTINATIONGODOWN>
<VOUCHERDESTINATIONGODOWN>Main Location</VOUCHERDESTINATIONGODOWN>
<VOUCHERSOURCEGODOWN>Main Location</VOUCHERSOURCEGODOWN>
<DIFFACTUALQTY>No</DIFFACTUALQTY>
<FORJOBCOSTING>Yes</FORJOBCOSTING>
<ISINVOICE>No</ISINVOICE>
<MFGJOURNAL>No</MFGJOURNAL>
<VCHPROPISSTKJRNL>Yes</VCHPROPISSTKJRNL>
<ISNEGISPOSSET>Yes</ISNEGISPOSSET>
<ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
<NUMBERINGSTYLE>Auto Renumber</NUMBERINGSTYLE>
<VOUCHERNUMBERSERIES>Default</VOUCHERNUMBERSERIES>
<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>47gm. 1lt. Pet Bottle</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY> 2016 pc</ACTUALQTY>
 <BILLEDQTY> 2016 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT>
  <ACTUALQTY> 2016 pc</ACTUALQTY>
  <BILLEDQTY> 2016 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>
<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>PET PREFORMS</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>0/kg</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY> 94 kg 752 gm.</ACTUALQTY>
 <BILLEDQTY> 94 kg 752 gm.</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT>
  <ACTUALQTY> 94 kg 752 gm.</ACTUALQTY>
  <BILLEDQTY> 94 kg 752 gm.</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>
<INVENTORYENTRIESIN.LIST>
 <STOCKITEMNAME>47gm. 1lt. Pet Bottle</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY> 2016 pc</ACTUALQTY>
 <BILLEDQTY> 2016 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT>
  <ACTUALQTY> 2016 pc</ACTUALQTY>
  <BILLEDQTY> 2016 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESIN.LIST>
<INVENTORYENTRIESOUT.LIST>
 <STOCKITEMNAME>PET PREFORMS</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>0/kg</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY> 94 kg 752 gm.</ACTUALQTY>
 <BILLEDQTY> 94 kg 752 gm.</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT>
  <ACTUALQTY> 94 kg 752 gm.</ACTUALQTY>
  <BILLEDQTY> 94 kg 752 gm.</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESOUT.LIST>
</VOUCHER>
</TALLYMESSAGE>
</DATA>
</BODY>
</ENVELOPE>
'@
$r = Invoke-WebRequest -Uri 'http://localhost:9000' -Method Post -Body $body -TimeoutSec 30 -UseBasicParsing
$r.Content
