import urllib.request

xml = '''<ENVELOPE>
<HEADER><VERSION>1</VERSION><TALLYREQUEST>Import</TALLYREQUEST><TYPE>Data</TYPE><ID>Vouchers</ID></HEADER>
<BODY><DESC>
<STATICVARIABLES>
<SVCURRENTCOMPANY>PAVISHA POLYMERS</SVCURRENTCOMPANY>
</STATICVARIABLES>
</DESC>
<DATA>
<TALLYMESSAGE>
<VOUCHER VCHTYPE="Manufacturing Journal" ACTION="Create" OBJVIEW="Multi Consumption Voucher View">
<DATE>20250701</DATE>
<EFFECTIVEDATE>20250701</EFFECTIVEDATE>
<VOUCHERTYPENAME>Manufacturing Journal</VOUCHERTYPENAME>
<NARRATION>Manufacturing for Sale Invoice #43 dated 23-Jul-25 (Arun Book Depo)</NARRATION>
<DESTINATIONGODOWN>Main Location</DESTINATIONGODOWN>
<VOUCHERDESTINATIONGODOWN>Main Location</VOUCHERDESTINATIONGODOWN>
<VOUCHERSOURCEGODOWN>Main Location</VOUCHERSOURCEGODOWN>
<FORJOBCOSTING>Yes</FORJOBCOSTING>
<VCHPROPISSTKJRNL>Yes</VCHPROPISSTKJRNL>
<ISNEGISPOSSET>Yes</ISNEGISPOSSET>
<ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
<DIFFACTUALQTY>No</DIFFACTUALQTY>
<NUMBERINGSTYLE>Auto Renumber</NUMBERINGSTYLE>
<VOUCHERNUMBERSERIES>Default</VOUCHERNUMBERSERIES>

<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>47gm. 1lt. Pet Bottle</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY> 2016 pc</ACTUALQTY>
 <BILLEDQTY> 2016 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT>
  <ACTUALQTY> 2016 pc</ACTUALQTY>
  <BILLEDQTY> 2016 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>

<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>45gm. Pet Bottle+Flip Top Cap</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY> 720 pc</ACTUALQTY>
 <BILLEDQTY> 720 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT>
  <ACTUALQTY> 720 pc</ACTUALQTY>
  <BILLEDQTY> 720 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>

<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>PET PREFORMS</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>0/kg</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY> 127 kg 152 gm.</ACTUALQTY>
 <BILLEDQTY> 127 kg 152 gm.</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT>
  <ACTUALQTY> 127 kg 152 gm.</ACTUALQTY>
  <BILLEDQTY> 127 kg 152 gm.</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>

<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>Cap 46mm Flip Top</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY> 720 pc</ACTUALQTY>
 <BILLEDQTY> 720 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT>
  <ACTUALQTY> 720 pc</ACTUALQTY>
  <BILLEDQTY> 720 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>

<INVENTORYENTRIESIN.LIST>
 <STOCKITEMNAME>47gm. 1lt. Pet Bottle</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY> 2016 pc</ACTUALQTY>
 <BILLEDQTY> 2016 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT>
  <ACTUALQTY> 2016 pc</ACTUALQTY>
  <BILLEDQTY> 2016 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESIN.LIST>

<INVENTORYENTRIESIN.LIST>
 <STOCKITEMNAME>45gm. Pet Bottle+Flip Top Cap</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY> 720 pc</ACTUALQTY>
 <BILLEDQTY> 720 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT>
  <ACTUALQTY> 720 pc</ACTUALQTY>
  <BILLEDQTY> 720 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESIN.LIST>

<INVENTORYENTRIESOUT.LIST>
 <STOCKITEMNAME>PET PREFORMS</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>0/kg</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY> 127 kg 152 gm.</ACTUALQTY>
 <BILLEDQTY> 127 kg 152 gm.</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT>
  <ACTUALQTY> 127 kg 152 gm.</ACTUALQTY>
  <BILLEDQTY> 127 kg 152 gm.</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESOUT.LIST>

<INVENTORYENTRIESOUT.LIST>
 <STOCKITEMNAME>Cap 46mm Flip Top</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE>
 <AMOUNT>0</AMOUNT>
 <ACTUALQTY> 720 pc</ACTUALQTY>
 <BILLEDQTY> 720 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST>
  <GODOWNNAME>Main Location</GODOWNNAME>
  <BATCHNAME>Primary Batch</BATCHNAME>
  <AMOUNT>0</AMOUNT>
  <ACTUALQTY> 720 pc</ACTUALQTY>
  <BILLEDQTY> 720 pc</BILLEDQTY>
 </BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESOUT.LIST>

</VOUCHER>
</TALLYMESSAGE>
</DATA>
</BODY>
</ENVELOPE>'''

req = urllib.request.Request('http://localhost:9000', data=xml.encode('utf-8'), method='POST')
req.add_header('Content-Type', 'text/xml; charset=utf-8')
resp = urllib.request.urlopen(req, timeout=30)
print(resp.read().decode('utf-8'))
