$body = @'
<ENVELOPE>
<HEADER><VERSION>1</VERSION><TALLYREQUEST>Import</TALLYREQUEST><TYPE>Data</TYPE><ID>All Masters</ID></HEADER>
<BODY><DESC>
<STATICVARIABLES>
<SVCURRENTCOMPANY>PAVISHA POLYMERS</SVCURRENTCOMPANY>
</STATICVARIABLES>
</DESC>
<DATA>
<TALLYMESSAGE>
<COMPANY NAME="PAVISHA POLYMERS" ACTION="Alter">
<NAME.LIST><NAME>PAVISHA POLYMERS</NAME></NAME.LIST>
<ISINTEGRATEACCWITHSTOCK>No</ISINTEGRATEACCWITHSTOCK>
</COMPANY>
</TALLYMESSAGE>
</DATA>
</BODY>
</ENVELOPE>
'@
$r = Invoke-WebRequest -Uri 'http://localhost:9000' -Method Post -Body $body -TimeoutSec 30 -UseBasicParsing
$r.Content
