import urllib.request

def test_date(date_str, label):
    xml = f'''<ENVELOPE>
<HEADER><VERSION>1</VERSION><TALLYREQUEST>Import</TALLYREQUEST><TYPE>Data</TYPE><ID>Vouchers</ID></HEADER>
<BODY><DESC>
<STATICVARIABLES><SVCURRENTCOMPANY>PAVISHA POLYMERS</SVCURRENTCOMPANY></STATICVARIABLES>
</DESC>
<DATA><TALLYMESSAGE>
<VOUCHER VCHTYPE="Manufacturing Journal" ACTION="Create" OBJVIEW="Multi Consumption Voucher View">
<DATE>{date_str}</DATE><EFFECTIVEDATE>{date_str}</EFFECTIVEDATE>
<VOUCHERTYPENAME>Manufacturing Journal</VOUCHERTYPENAME>
<NARRATION>LIMIT TEST {label}</NARRATION>
<DESTINATIONGODOWN>Main Location</DESTINATIONGODOWN>
<VOUCHERDESTINATIONGODOWN>Main Location</VOUCHERDESTINATIONGODOWN>
<VOUCHERSOURCEGODOWN>Main Location</VOUCHERSOURCEGODOWN>
<FORJOBCOSTING>Yes</FORJOBCOSTING><VCHPROPISSTKJRNL>Yes</VCHPROPISSTKJRNL>
<ISNEGISPOSSET>Yes</ISNEGISPOSSET><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
<DIFFACTUALQTY>No</DIFFACTUALQTY>
<NUMBERINGSTYLE>Auto Renumber</NUMBERINGSTYLE><VOUCHERNUMBERSERIES>Default</VOUCHERNUMBERSERIES>
<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>47gm. 1lt. Pet Bottle</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE><AMOUNT>0</AMOUNT><ACTUALQTY> 1 pc</ACTUALQTY><BILLEDQTY> 1 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST><BATCHNAME>Primary Batch</BATCHNAME><AMOUNT>0</AMOUNT><ACTUALQTY> 1 pc</ACTUALQTY><BILLEDQTY> 1 pc</BILLEDQTY></BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>
<ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>PET PREFORMS</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>0/kg</RATE><AMOUNT>0</AMOUNT><ACTUALQTY> 0 kg 47 gm.</ACTUALQTY><BILLEDQTY> 0 kg 47 gm.</BILLEDQTY>
 <BATCHALLOCATIONS.LIST><GODOWNNAME>Main Location</GODOWNNAME><BATCHNAME>Primary Batch</BATCHNAME><AMOUNT>0</AMOUNT><ACTUALQTY> 0 kg 47 gm.</ACTUALQTY><BILLEDQTY> 0 kg 47 gm.</BILLEDQTY></BATCHALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>
<INVENTORYENTRIESIN.LIST>
 <STOCKITEMNAME>47gm. 1lt. Pet Bottle</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <RATE>0/pc</RATE><AMOUNT>0</AMOUNT><ACTUALQTY> 1 pc</ACTUALQTY><BILLEDQTY> 1 pc</BILLEDQTY>
 <BATCHALLOCATIONS.LIST><GODOWNNAME>Main Location</GODOWNNAME><BATCHNAME>Primary Batch</BATCHNAME><AMOUNT>0</AMOUNT><ACTUALQTY> 1 pc</ACTUALQTY><BILLEDQTY> 1 pc</BILLEDQTY></BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESIN.LIST>
<INVENTORYENTRIESOUT.LIST>
 <STOCKITEMNAME>PET PREFORMS</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <RATE>0/kg</RATE><AMOUNT>0</AMOUNT><ACTUALQTY> 0 kg 47 gm.</ACTUALQTY><BILLEDQTY> 0 kg 47 gm.</BILLEDQTY>
 <BATCHALLOCATIONS.LIST><GODOWNNAME>Main Location</GODOWNNAME><BATCHNAME>Primary Batch</BATCHNAME><AMOUNT>0</AMOUNT><ACTUALQTY> 0 kg 47 gm.</ACTUALQTY><BILLEDQTY> 0 kg 47 gm.</BILLEDQTY></BATCHALLOCATIONS.LIST>
</INVENTORYENTRIESOUT.LIST>
</VOUCHER>
</TALLYMESSAGE></DATA></BODY></ENVELOPE>'''
    req = urllib.request.Request('http://localhost:9000', data=xml.encode('utf-8'), method='POST')
    req.add_header('Content-Type', 'text/xml; charset=utf-8')
    resp = urllib.request.urlopen(req, timeout=30)
    result = resp.read().decode('utf-8')
    ok = '<CREATED>1</CREATED>' in result
    print(f"  {label}: {'OK' if ok else 'FAIL'}")
    return ok

# Test: can we still create on 1st of months? (known good dates)
test_date("20250901", "1-Sep-25")
test_date("20251101", "1-Nov-25")

# Test: try mid-month on a fresh month we haven't tested
test_date("20250915", "15-Sep-25")
test_date("20250910", "10-Sep-25")
test_date("20250905", "5-Sep-25")
test_date("20250903", "3-Sep-25")
test_date("20250902", "2-Sep-25")
