$body = @'
<ENVELOPE>
<HEADER><VERSION>1</VERSION><TALLYREQUEST>Export</TALLYREQUEST><TYPE>Collection</TYPE><ID>MfgVouchers</ID></HEADER>
<BODY><DESC>
<STATICVARIABLES>
<SVCURRENTCOMPANY>PAVISHA POLYMERS</SVCURRENTCOMPANY>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
<SVFROMDATE>20260101</SVFROMDATE>
<SVTODATE>20261231</SVTODATE>
</STATICVARIABLES>
<TDL><TDLMESSAGE>
<COLLECTION NAME="MfgVouchers" ISMODIFY="No">
<TYPE>Voucher</TYPE>
<CHILDOF>Manufacturing Journal</CHILDOF>
<BELONGSTO>Yes</BELONGSTO>
<FETCH>*, ALLINVENTORYENTRIES.LIST, INVENTORYENTRIESIN.LIST, INVENTORYENTRIESOUT.LIST</FETCH>
</COLLECTION>
</TDLMESSAGE></TDL>
</DESC></BODY>
</ENVELOPE>
'@
$r = Invoke-WebRequest -Uri 'http://localhost:9000' -Method Post -Body $body -TimeoutSec 30 -UseBasicParsing
$r.Content | Out-File -FilePath 'D:\openclaw\workspace\existing_mfg.xml' -Encoding UTF8
Write-Host "Saved. Size: $((Get-Item 'D:\openclaw\workspace\existing_mfg.xml').Length) bytes"
